service: news-feed

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  stage: dev
  profile: classting-iam

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}

